### ISSUE TITLE
local.ERROR: syntax error, unexpected identifier "version"

### ISSUE THREAD

**Issue by Schwenniii** [mitydigital/statamic-rss-feed#2]
i get the following error local.ERROR: syntax error, unexpected identifier "version"

if i remove version attribute from rss template i get the same error but with encoding instead version

**Comment by martyf** [comment]
Can you please provide further information, ideally:
- the exact error,
- steps to replicate the error,
- any content entries that may be triggering the error, and if possible
- a repo that exhibits the error

**Comment by Schwenniii** [comment]
i spend some time and i found the problem. The <? tag from xml is the Problem on Servers with active php short tags
the solution is to replace `<?xml version="1.0" encoding="utf-8"?>` on blade template

with 
```
<?php
echo '<?xml version="1.0" encoding="utf-8"?>';
?>
```

**Comment by martyf** [comment]
Cool bananas - did your IDE change the formatting perhaps as that line break isn’t in the base template? Glad you got it sorted.

**Comment by Schwenniii** [comment]
no the template comes directly from composer

**Comment by martyf** [comment]
I've just added a minor version release that addresses this - I misread your fix originally about short tags. Thanks for raising this.
